# YouTube Live daemon - Task Scheduler registration
# Triggers: at logon + daily 20:00 backup (IgnoreNew skips if already running)
# Launch chain: Task Scheduler -> wscript run_check_live.vbs (zero popup) -> python check_live.py
# Logging is done by check_live.py itself (check_live.log), no shell redirection needed

$taskName = "YT-LiveCheck"
$scriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$scriptPath = Join-Path $scriptDir "check_live.py"
$vbsPath = Join-Path $scriptDir "run_check_live.vbs"

# Locate python.exe: PATH first, then the py launcher.
# Store-alias stubs under WindowsApps are skipped (they only open the Store).
$pythonExe = $null
$candidate = (Get-Command python.exe -ErrorAction SilentlyContinue).Source
if ($candidate -and $candidate -notlike "*WindowsApps*") { $pythonExe = $candidate }

if (-not $pythonExe) {
    $pyLauncher = (Get-Command py.exe -ErrorAction SilentlyContinue).Source
    if ($pyLauncher) {
        $resolved = & $pyLauncher -3 -c "import sys; print(sys.executable)"
        if ($resolved -and (Test-Path $resolved)) { $pythonExe = $resolved }
    }
}

if (-not $pythonExe) {
    Write-Host "ERROR: python not found. Install Python 3.10 or newer and tick 'Add python.exe to PATH'."
    exit 1
}
Write-Host "python: $pythonExe"

# Generate vbs launcher. It WAITS for python (last arg True) so Task Scheduler
# sees the task as Running -> the 20:00 backup trigger only revives a dead daemon.
$envPath = Join-Path $scriptDir ".env"
$vbsTemplate = @'
' daemon launcher (auto-generated by setup_task.ps1, do not edit)
Set shell = CreateObject("WScript.Shell")
Set fso = CreateObject("Scripting.FileSystemObject")
Set env = shell.Environment("Process")
envFile = "__ENV__"
If fso.FileExists(envFile) Then
    Set f = fso.OpenTextFile(envFile, 1)
    Do While Not f.AtEndOfStream
        line = Trim(f.ReadLine)
        If Len(line) > 0 And Left(line, 1) <> "#" Then
            pos = InStr(line, "=")
            If pos > 1 Then
                env(Left(line, pos - 1)) = Mid(line, pos + 1)
            End If
        End If
    Loop
    f.Close
End If
shell.Run """__PY__"" -u ""__SCRIPT__""", 0, True
'@
$vbsContent = $vbsTemplate.Replace("__PY__", $pythonExe).Replace("__SCRIPT__", $scriptPath).Replace("__ENV__", $envPath)
Set-Content -Path $vbsPath -Value $vbsContent -Encoding ASCII
Write-Host "vbs launcher written: $vbsPath"

# Kill any old daemon instance to avoid doubles
$procs = Get-CimInstance Win32_Process -Filter "Name='python.exe'" -ErrorAction SilentlyContinue |
    Where-Object { $_.CommandLine -like '*check_live.py*' }
foreach ($p in $procs) {
    Stop-Process -Id $p.ProcessId -Force
    Write-Host "Killed old daemon PID $($p.ProcessId)"
}

# Remove old task
$existing = Get-ScheduledTask -TaskName $taskName -ErrorAction SilentlyContinue
if ($existing) {
    Unregister-ScheduledTask -TaskName $taskName -Confirm:$false
    Write-Host "Old task removed"
}

$action = New-ScheduledTaskAction -Execute "wscript.exe" -Argument "//B //Nologo `"$vbsPath`"" -WorkingDirectory $scriptDir

$trigLogon = New-ScheduledTaskTrigger -AtLogOn -User $env:USERNAME
$trigDaily = New-ScheduledTaskTrigger -Daily -At "20:00"

$settings = New-ScheduledTaskSettingsSet `
    -StartWhenAvailable `
    -ExecutionTimeLimit (New-TimeSpan -Seconds 0) `
    -AllowStartIfOnBatteries `
    -DontStopIfGoingOnBatteries `
    -MultipleInstances IgnoreNew
$settings.IdleSettings.StopOnIdleEnd = $false

Register-ScheduledTask `
    -TaskName $taskName `
    -Action $action `
    -Trigger @($trigLogon, $trigDaily) `
    -Settings $settings `
    -Description "All-day live watch for the configured YouTube channel (feed poll 60s, videos.list on change)" `
    -RunLevel Limited

Write-Host "Task '$taskName' registered (logon + daily 20:00 backup)."

Start-ScheduledTask -TaskName $taskName
Write-Host "Task started."
